### ISSUE TITLE
Songs stuck in the same branch

### ISSUE THREAD

**Issue by SHNORTT** [Pithaya/spicetify-apps-dist#31]
There is some songs that have a branch that keeps repeatin non stop doesnt matter how low i put the probability to it will repeat, example linked below

https://github.com/Pithaya/spicetify-apps-dist/assets/91035633/6ba5bdea-2152-428c-bdfc-33fda3a21828

**Comment by Blaubeermuffin** [comment]
I second this bug report, as I have noticed the same issue on multiple songs as well.

After tinkering around with some settings, I figured out that it's only the last branch in a song, where this happens consistently for me. 

This feels like the Eternal Jukebox is set to playing a song literally for eternity.
I'd prefer it to only lengthen songs though and respect branching probabilities and eventually continue on to the next song, instead of forcing the last branch to loop 100% of the time.
This could be an option in the settings, if you truly wish to force playing for eternity (e.g. named "force last branch hopping" or "play for eternity" or similar).

As a user of the Eternal Jukebox, I'd welcome a setting like that.
